let container = document.getElementById("container");

let gridPiece1 = document.createElement("div");
let gridPiece2 = document.createElement("div");
let gridPiece3 = document.createElement("div");
let gridPiece4 = document.createElement("div");
let gridPiece5 = document.createElement("div");
let gridPiece6 = document.createElement("div");
let gridPiece7 = document.createElement("div");
let gridPiece8 = document.createElement("div");
let gridPiece9 = document.createElement("div");
let gridPiece10 = document.createElement("div");
let gridPiece11 = document.createElement("div");
let gridPiece12 = document.createElement("div");
let gridPiece13 = document.createElement("div");
let gridPiece14 = document.createElement("div");
let gridPiece15 = document.createElement("div");
let gridPiece16 = document.createElement("div");

gridPiece1.className = "grid-piece";
gridPiece2.className = "grid-piece";
gridPiece3.className = "grid-piece";
gridPiece4.className = "grid-piece";
gridPiece5.className = "grid-piece";
gridPiece6.className = "grid-piece";
gridPiece7.className = "grid-piece";
gridPiece8.className = "grid-piece";
gridPiece9.className = "grid-piece";
gridPiece10.className = "grid-piece";
gridPiece11.className = "grid-piece";
gridPiece12.className = "grid-piece";
gridPiece13.className = "grid-piece";
gridPiece14.className = "grid-piece";
gridPiece15.className = "grid-piece";
gridPiece16.className = "grid-piece";

container.appendChild(gridPiece1);
container.appendChild(gridPiece2);
container.appendChild(gridPiece3);
container.appendChild(gridPiece4);
container.appendChild(gridPiece5);
container.appendChild(gridPiece6);
container.appendChild(gridPiece7);
container.appendChild(gridPiece8);
container.appendChild(gridPiece9);
container.appendChild(gridPiece10);
container.appendChild(gridPiece11);
container.appendChild(gridPiece12);
container.appendChild(gridPiece13);
container.appendChild(gridPiece14);
container.appendChild(gridPiece15);
container.appendChild(gridPiece16);
